import {
  createDefaultV2Streams,
  createV2AudioStream,
  createV2AttachmentStream,
  createV2DataStream,
  createV2EnsureAudioStreamOperation,
  createV2RemoveDataStreamsOperation,
  createV2RemoveStreamByPropertyOperation,
  createV2RemoveSubtitlesOperation,
  createV2ReorderStreamsOperation,
  createV2SetContainerOperation,
  createV2SubtitleStream,
  createV2VideoEncoderOperation,
  createV2VideoStream,
  createV2MockEncoder,
  createV2VideoResolutionOperation,
} from './scenarioUtils';
import type { IffmpegCommandV2Scenario } from './scenarioUtils';

const streamScenarios: IffmpegCommandV2Scenario[] = [
  {
    id: 'copy-passthrough',
    description: 'No v2 render operations copy every stream without processing',
    streams: createDefaultV2Streams(),
    operations: [],
    expected: {
      shouldProcess: false,
      container: 'mp4',
      sourceIndexes: [0, 1],
      codecTypes: ['video', 'audio'],
      spawnArgs: [
        '-y',
        '-i',
        '/tmp/source.mp4',
        '-map',
        '0:0',
        '-c:0',
        'copy',
        '-map',
        '0:1',
        '-c:1',
        'copy',
      ],
    },
  },
  {
    id: 'attached-picture-is-not-treated-as-video',
    description: 'Attached pictures are normalized to attachments and do not receive video encode or filter args',
    streams: [
      createV2VideoStream({ index: 0 }),
      createV2AudioStream({ index: 1 }),
      createV2AttachmentStream({ index: 2 }),
    ],
    operations: [
      createV2VideoEncoderOperation({
        hardwareEncoding: false,
        hardwareType: 'auto',
        hardwareDecoding: false,
      }),
      createV2VideoResolutionOperation('1080p'),
    ],
    encoder: createV2MockEncoder({
      encoder: 'libx265',
      inputArgs: [],
      isGpu: false,
    }),
    expected: {
      shouldProcess: true,
      container: 'mp4',
      sourceIndexes: [0, 1, 2],
      codecTypes: ['video', 'audio', 'attachment'],
      spawnArgs: [
        '-y',
        '-i',
        '/tmp/source.mp4',
        '-map',
        '0:0',
        '-c:0',
        'libx265',
        '-crf',
        '25',
        '-preset',
        'fast',
        '-filter:v:0',
        'scale=1920:-2',
        '-map',
        '0:1',
        '-c:1',
        'copy',
        '-map',
        '0:2',
        '-c:2',
        'copy',
      ],
    },
  },
  {
    id: 'remove-subtitles-and-reorder-streams',
    description: 'Subtitle removal followed by audio-first reordering keeps output indexes stable',
    streams: [
      createV2VideoStream({ index: 0 }),
      createV2AudioStream({ index: 1 }),
      createV2SubtitleStream({ index: 2 }),
      createV2AudioStream({
        index: 3,
        codec_name: 'ac3',
        channels: 6,
        tags: {
          language: 'fre',
        },
      }),
    ],
    operations: [
      createV2RemoveSubtitlesOperation(),
      createV2ReorderStreamsOperation({
        processOrder: 'streamTypes',
        languages: '',
        channels: '',
        codecs: '',
        streamTypes: 'audio,video',
      }),
    ],
    expected: {
      shouldProcess: true,
      container: 'mp4',
      sourceIndexes: [1, 3, 0],
      codecTypes: ['audio', 'audio', 'video'],
      spawnArgs: [
        '-y',
        '-i',
        '/tmp/source.mp4',
        '-map',
        '0:1',
        '-c:0',
        'copy',
        '-map',
        '0:3',
        '-c:1',
        'copy',
        '-map',
        '0:0',
        '-c:2',
        'copy',
      ],
    },
  },
  {
    id: 'remove-stream-by-nested-property',
    description: 'Nested stream properties can remove only matching streams while preserving later source indexes',
    streams: [
      createV2VideoStream({ index: 0 }),
      createV2AudioStream({ index: 1 }),
      createV2AudioStream({
        index: 2,
        codec_name: 'ac3',
        channels: 6,
        tags: {
          language: 'fre',
        },
      }),
      createV2SubtitleStream({ index: 3 }),
    ],
    operations: [
      createV2RemoveStreamByPropertyOperation({
        codecType: 'audio',
        propertyToCheck: 'tags.language',
        valuesToRemove: 'fre',
        condition: 'equals',
      }),
    ],
    expected: {
      shouldProcess: true,
      container: 'mp4',
      sourceIndexes: [0, 1, 3],
      codecTypes: ['video', 'audio', 'subtitle'],
      jobLogs: [
        'Keep stream index 1 because tags.language of eng equals fre\n',
        'Removing stream index 2 because tags.language of fre equals fre\n',
      ],
      spawnArgs: [
        '-y',
        '-i',
        '/tmp/source.mp4',
        '-map',
        '0:0',
        '-c:0',
        'copy',
        '-map',
        '0:1',
        '-c:1',
        'copy',
        '-map',
        '0:3',
        '-c:2',
        'copy',
      ],
    },
  },
  {
    id: 'ensure-downmixed-audio-stream',
    description: 'Ensure audio adds a new derived stream with scoped output indexes',
    streams: [
      createV2VideoStream({ index: 0 }),
      createV2AudioStream({ index: 1 }),
      createV2AudioStream({
        index: 2,
        codec_name: 'ac3',
        channels: 6,
      }),
    ],
    operations: [
      createV2EnsureAudioStreamOperation({
        audioEncoder: 'ac3',
        language: 'eng',
        channels: '2',
        enableBitrate: true,
        bitrate: '640k',
        enableSamplerate: true,
        samplerate: '48000',
      }),
    ],
    expected: {
      shouldProcess: true,
      container: 'mp4',
      sourceIndexes: [0, 1, 2, 2],
      codecTypes: ['video', 'audio', 'audio', 'audio'],
      jobLogs: [
        'Adding eng stream in ac3, 2 channels \n',
      ],
      spawnArgs: [
        '-y',
        '-i',
        '/tmp/source.mp4',
        '-map',
        '0:0',
        '-c:0',
        'copy',
        '-map',
        '0:1',
        '-c:1',
        'copy',
        '-map',
        '0:2',
        '-c:2',
        'copy',
        '-map',
        '0:2',
        '-c:3',
        'ac3',
        '-ac',
        '2',
        '-b:a:2',
        '640k',
        '-ar',
        '48000',
      ],
    },
  },
  {
    id: 'mkv-container-conform',
    description: 'Changing to MKV with force conform removes unsupported data and mov_text streams',
    streams: [
      createV2VideoStream({ index: 0 }),
      createV2AudioStream({ index: 1 }),
      createV2SubtitleStream({
        index: 2,
        codec_name: 'mov_text',
      }),
      createV2DataStream({ index: 3 }),
    ],
    operations: [
      createV2SetContainerOperation({
        container: 'mkv',
        forceConform: true,
      }),
    ],
    expected: {
      shouldProcess: true,
      container: 'mkv',
      sourceIndexes: [0, 1],
      codecTypes: ['video', 'audio'],
      spawnArgs: [
        '-y',
        '-i',
        '/tmp/source.mp4',
        '-map',
        '0:0',
        '-c:0',
        'copy',
        '-map',
        '0:1',
        '-c:1',
        'copy',
      ],
    },
  },
  {
    id: 'transport-stream-remux-adds-genpts',
    description: 'Changing MPEG-TS-like inputs to another container adds genpts before the input',
    streams: createDefaultV2Streams(),
    inputFile: {
      id: '/tmp/source.ts',
      container: 'ts',
    },
    operations: [
      createV2SetContainerOperation({
        container: 'mkv',
        forceConform: false,
      }),
    ],
    expected: {
      shouldProcess: true,
      container: 'mkv',
      sourceIndexes: [0, 1],
      codecTypes: ['video', 'audio'],
      spawnArgs: [
        '-y',
        '-fflags',
        '+genpts',
        '-i',
        '/tmp/source.ts',
        '-map',
        '0:0',
        '-c:0',
        'copy',
        '-map',
        '0:1',
        '-c:1',
        'copy',
      ],
    },
  },
  {
    id: 'changed-input-file-log',
    description: 'Execute logs when the current input changed after Begin Command',
    streams: createDefaultV2Streams(),
    operations: [],
    sourceFileId: '/tmp/old-source.mp4',
    expected: {
      shouldProcess: false,
      container: 'mp4',
      sourceIndexes: [0, 1],
      codecTypes: ['video', 'audio'],
      jobLogs: [
        'FFmpeg command v2 input changed between Begin Command and Execute; rendering from current input file.',
      ],
      spawnArgs: [
        '-y',
        '-i',
        '/tmp/source.mp4',
        '-map',
        '0:0',
        '-c:0',
        'copy',
        '-map',
        '0:1',
        '-c:1',
        'copy',
      ],
    },
  },
  {
    id: 'no-streams-mapped-error',
    description: 'Removing all mapped streams fails clearly',
    streams: [
      createV2SubtitleStream({
        index: 0,
      }),
      createV2DataStream({
        index: 1,
      }),
    ],
    operations: [
      createV2RemoveSubtitlesOperation(),
      createV2RemoveDataStreamsOperation(),
    ],
    expected: {
      errorMessage: 'No streams mapped for new file',
      jobLogs: [
        'No streams mapped for new file',
      ],
    },
  },
];

export default streamScenarios;
