"use strict";
var details = function () { return ({
    name: 'Basic Video Template',
    description: 'Basic Video Template',
    tags: 'video',
    flowPlugins: [
        {
            id: 'nr55HwObs',
            version: '1.0.0',
            pluginName: 'inputFile',
            inputsDB: {},
            position: {
                x: 371.99540048613267,
                y: -463.08388975391864,
            },
            data: {
                label: 'Input File',
            },
            sourceRepo: 'Community',
        },
        {
            id: 'aDDcNO50Q',
            version: '1.0.0',
            pluginName: 'checkFileMedium',
            inputsDB: {},
            position: {
                x: 529.392455443893,
                y: -349.448086326927,
            },
            data: {
                label: 'Check File Medium',
            },
            sourceRepo: 'Community',
        },
        {
            id: 'dBwjiWjfA',
            version: '1.0.0',
            pluginName: 'replaceOriginalFile',
            inputsDB: {},
            position: {
                x: 517.8566785616271,
                y: 145.89446592709146,
            },
            data: {
                label: 'Replace Original File',
            },
            sourceRepo: 'Community',
        },
        {
            id: '1m231hS5K',
            version: '1.0.0',
            pluginName: 'ffmpegCommandSetVideoEncoder',
            inputsDB: {},
            position: {
                x: 104.71582826971436,
                y: -44.833187887976514,
            },
            data: {
                label: 'Set Video Encoder',
            },
            sourceRepo: 'Community',
        },
        {
            id: 'iYEwAG4rk',
            version: '1.0.0',
            pluginName: 'ffmpegCommandStart',
            inputsDB: {},
            position: {
                x: 138.43458422405857,
                y: -149.36438875566702,
            },
            data: {
                label: 'Start',
            },
            sourceRepo: 'Community',
        },
        {
            id: 'staFGJ7lQ',
            version: '1.0.0',
            pluginName: 'ffmpegCommandExecute',
            inputsDB: {},
            position: {
                x: 104.4813203353468,
                y: 63.43024405079595,
            },
            data: {
                label: 'Execute',
            },
            sourceRepo: 'Community',
        },
        {
            id: '3sQBco3U6',
            version: '1.0.0',
            pluginName: 'checkVideoCodec',
            inputsDB: {},
            position: {
                x: 252.92777615144564,
                y: -274.3710285987198,
            },
            data: {
                label: 'Check if HEVC',
            },
            sourceRepo: 'Community',
        },
    ],
    flowEdges: [
        {
            source: 'nr55HwObs',
            sourceHandle: '1',
            target: 'aDDcNO50Q',
            targetHandle: null,
            animated: true,
            type: 'smoothstep',
            id: 'reactflow__edge-nr55HwObs1-aDDcNO50Q',
        },
        {
            source: 'aDDcNO50Q',
            sourceHandle: '3',
            target: 'dBwjiWjfA',
            targetHandle: null,
            animated: true,
            type: 'smoothstep',
            id: 'reactflow__edge-aDDcNO50Q3-dBwjiWjfA',
        },
        {
            source: 'aDDcNO50Q',
            sourceHandle: '2',
            target: 'dBwjiWjfA',
            targetHandle: null,
            animated: true,
            type: 'smoothstep',
            id: 'reactflow__edge-aDDcNO50Q2-dBwjiWjfA',
        },
        {
            source: 'iYEwAG4rk',
            sourceHandle: '1',
            target: '1m231hS5K',
            targetHandle: null,
            animated: true,
            type: 'smoothstep',
            id: 'reactflow__edge-iYEwAG4rk1-1m231hS5K',
        },
        {
            source: '1m231hS5K',
            sourceHandle: '1',
            target: 'staFGJ7lQ',
            targetHandle: null,
            animated: true,
            type: 'smoothstep',
            id: 'reactflow__edge-1m231hS5K1-staFGJ7lQ',
        },
        {
            source: 'staFGJ7lQ',
            sourceHandle: '2',
            target: 'dBwjiWjfA',
            targetHandle: null,
            animated: true,
            type: 'smoothstep',
            id: 'reactflow__edge-staFGJ7lQ2-dBwjiWjfA',
        },
        {
            source: 'staFGJ7lQ',
            sourceHandle: '1',
            target: 'dBwjiWjfA',
            targetHandle: null,
            animated: true,
            type: 'smoothstep',
            id: 'reactflow__edge-staFGJ7lQ1-dBwjiWjfA',
        },
        {
            source: 'aDDcNO50Q',
            sourceHandle: '1',
            target: '3sQBco3U6',
            targetHandle: null,
            animated: true,
            type: 'smoothstep',
            id: 'reactflow__edge-aDDcNO50Q1-3sQBco3U6',
        },
        {
            source: '3sQBco3U6',
            sourceHandle: '1',
            target: 'dBwjiWjfA',
            targetHandle: null,
            animated: true,
            type: 'smoothstep',
            id: 'reactflow__edge-3sQBco3U61-dBwjiWjfA',
        },
        {
            source: '3sQBco3U6',
            sourceHandle: '2',
            target: 'iYEwAG4rk',
            targetHandle: null,
            animated: true,
            type: 'smoothstep',
            id: 'reactflow__edge-3sQBco3U62-iYEwAG4rk',
        },
    ],
}); };
module.exports.details = details;
